<?php

define('HIDDENCMS_DEBUG_BAR',  FALSE);
define('HIDDENCMS_SAFE_MODE',  FALSE);
define('HIDDENCMS_LOGS',       FALSE);
define('HIDDENCMS_LOGS_DB',    FALSE);
define('HIDDENCMS_LOGS_I18N',  FALSE);

define('NEOFRAG_DEBUG_BAR', HIDDENCMS_DEBUG_BAR);
define('NEOFRAG_SAFE_MODE', HIDDENCMS_SAFE_MODE);
define('NEOFRAG_LOGS',      HIDDENCMS_LOGS);
define('NEOFRAG_LOGS_DB',   HIDDENCMS_LOGS_DB);
define('NEOFRAG_LOGS_I18N', HIDDENCMS_LOGS_I18N);
