<?php
return [
    '5beec5f0' => 'Ordinateur',
    61526780 => 'Tablette paysage',
    '2da1d4dc' => 'Tablette portrait',
    'eaf7576f' => 'Titre',
    'cd643ef3' => 'Chargement en cours...',
    'aab95b9f' => 'Lignes',
    '6373f92b' => 'Colonnes',
    '0a60292c' => 'Taille de l\'écran',
    'ebb62dcb' => 'Widget sélectionné',
    '66905ebe' => 'Laissez ce champ vide pour ne pas afficher de titre.',
    'd2c0aec0' => 'Fermer',
    '51bac044' => 'Annuler',
    'f55495e0' => 'Valider',
    'fbb9ff8a' => 'Précédent',
    'a41dbf02' => 'Suivant',
    'e2503b39' => 'Revenir à la disposition commune',
    87715261 => 'Êtes-vous sûr(e) de vouloir revenir à la disposition commune ?<br />Toutes les <b>colonnes</b> et <b>widgets</b> associés à cette zone seront perdus.',
    'e949e68d' => 'Confirmation de suppression',
    '3dbe79b1' => 'Supprimer',
    'e5ee8140' => 'Apparence',
    '4dc1bc1a' => 'Configurer',
    'f7cbe9a7' => 'Êtes-vous sûr(e) de vouloir supprimer cette <b>ligne</b> ?<br />Toutes les <b>colonnes</b> et <b>widgets</b> contenus seront également supprimés.',
    '946af6d0' => 'Êtes-vous sûr(e) de vouloir supprimer cette <b>colonne</b> ?<br />Tous les <b>widgets</b> contenus seront également supprimés.',
];
